sudo: required
env:
  DOCKER_COMPOSE_VERSION: 1.7.1

services:
  - docker

before_install:
  - docker-compose version
  - docker version
  - chmod +x project.sh
  - ./project.sh setup
  - docker ps -a

script::
  - ./project.sh test ci
