version: '2'
services:
  node:
    image: mhart/alpine-node
    command: sleep 60
    working_dir: /opt
    volumes:
     - .:/opt
    depends_on:
     - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testing
