version: '2'
services:
  node:
    image: mhart/alpine-node
    command: sleep 60
    working_dir: /opt
    expose:
      - "3000"
    ports:
     - "3000:3000"
    volumes:
     - .:/opt
    depends_on:
     - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testing
