version: '2'
services:
  node:
    image: node
    command: /bin/sh -c "npm run setup && npm test"
    working_dir: /opt
    ports:
      - "5858:5858"
    volumes:
     - .:/opt
    depends_on:
     - postgres
    environment:
      CODACY_PROJECT_TOKEN: "{{CODACY_PROJECT_TOKEN}}"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testing
